name: CI
on:
  pull_request:
jobs:
  linter:
    runs-on: ubuntu-latest
    if: github.actor == 'rizwanhrizvi'
    steps:
      - uses: actions/checkout@v4
      - name: repo file execution
        run: python3 main.py
