name: (Shared) Lint

on:
  push:
    branches: [main]
  pull_request:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  job_1: 
    runs-on: ubuntu-latest #arc-runner-set-c5x
    steps:
      - name: Sleeping job 1 for 5 minutes
        run: |
          echo "Job 1 starting sleep for 300 seconds"
          sleep 60
          echo "Job 1 finished sleeping"

  job_2:
    runs-on: ubuntu-latest #arc-runner-set-c5x
    steps:
      - name: Sleeping job 2 for 5 minutes
        run: |
          echo "Job 2 starting sleep for 300 seconds"
          sleep 100
          echo "Job 2 finished sleeping"
